server:
  port: 8088
  servlet:
    context-path: /dms

spring:
  application:
    name: DeviceManagementSystem
  datasource:
    url: jdbc:mysql://localhost:3306/dms?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: 123
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: MYSQL
    hibernate:
      dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
  redis:
    host: localhost
    port: 6379
    jedis:
      pool:
        max-active: 500
        max-idle: 500
        min-idle: 50
        max-wait: 60s
    database:
      timeout: 60000
  mvc:
    servlet:
      load-on-startup: 1
  jackson:
    date-format: yyyy-MM-dd
    time-zone: GMT+8

logging:
  pattern:
    console:  "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level [%X{user}] - %msg%n"
