server:
  port: 8088
  servlet:
    context-path: /dms

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/dms?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: 123
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: localhost
    port: 6379
    #timeout: 60s   #数据库连接超时时间
    jedis:
      pool:
        max-active: 500
        max-idle: 500   #最大空闲连接数
        min-idle: 50    #最小空闲连接数
        max-wait: 60s   #最长等待时长
    database:
      timeout: 60000
  mvc:
    servlet:
      load-on-startup: 1
  jackson:
    date-format: yyyy-MM-dd
    time-zone: GMT+8

logging:
  pattern:
    console:  "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level [%X{user}] - %msg%n"
